all: exercice1 exercice2 exercice2 exercice3 exercice4 exercice5 exercice6 exercice7 exercice8 exercice9
exercice1: exercice1.c
	gcc -Wall -pedantic -ansi exercice1.c -o exercice1
exercice2: exercice2.c
	gcc -Wall -pedantic -ansi exercice2.c -o exercice2
exercice3: exercice3.c
	gcc -Wall -pedantic -ansi exercice3.c -o exercice3
exercice4: exercice4.c
	gcc -Wall -pedantic -ansi exercice4.c -o exercice4
exercice5: exercice5.c
	gcc -Wall -pedantic -ansi exercice5.c -o exercice5
exercice6: exercice6.c
	gcc -Wall -pedantic -ansi exercice6.c -o exercice6
exercice7: exercice7.c
	gcc -Wall -pedantic -ansi exercice7.c -o exercice7
exercice8: exercice8.c
	gcc -Wall -pedantic -ansi exercice8.c -o exercice8
exercice9: exercice9.c
	gcc -Wall -pedantic -ansi exercice9.c -o exercice9